language: ruby
sudo: required
rvm:
  - 2.3.0
before_script:
  - psql -c 'create database kiyoshikojin_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/initializers/kitaguchi.rb.example config/initializers/kitaguchi.rb
  - cp config/initializers/yahoo.rb.example config/initializers/yahoo.rb
before_install:
  - curl --silent --location https://github.com/pgroonga/pgroonga/raw/master/data/travis/setup.sh | sh
cache: bundler
addons:
  postgresql: "9.4"
notifications:
  email:
    - yune.kotomi+github@gmail.com
